services:
  backend:
    build: ./backend
    container_name: honeynet-manager
    network_mode: "host"
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - BACKEND_PORT=${BACKEND_PORT}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_HOST_DEVICE_IP: ${NEXT_PUBLIC_HOST_DEVICE_IP}
        NEXT_PUBLIC_RED_IP: ${NEXT_PUBLIC_RED_IP}
    container_name: honeynet-frontend
    network_mode: "host"
    env_file:
      - .env
    depends_on:
      - backend
    environment:
      - PORT=${FRONTEND_PORT}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_HOST_DEVICE_IP=${NEXT_PUBLIC_HOST_DEVICE_IP}
      - NEXT_PUBLIC_RED_IP=${NEXT_PUBLIC_RED_IP}

  db:
    image: postgres:15
    container_name: honeynet-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - honeynet-net

    nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  pgdata:

networks:
  honeynet-net:
