services:
  backend:
    build: ./backend
    container_name: honeynet-manager
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - honeynet-net

  frontend:
    build: ./frontend
    container_name: honeynet-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - honeynet-net

  db:
    image: postgres:15
    container_name: honeynet-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - honeynet-net

volumes:
  pgdata:

networks:
  honeynet-net:
    driver: bridge
