version: "3.9"

services:
  backend:
    build: ./backend
    container_name: honeynet-manager
    network_mode: "host"
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - BACKEND_PORT=${BACKEND_PORT}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: honeynet-frontend
    network_mode: "host"
    env_file:
      - .env
    depends_on:
      - backend
    environment:
      - PORT=${FRONTEND_PORT}

  db:
    image: postgres:15
    container_name: honeynet-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - honeynet-net

volumes:
  pgdata:

networks:
  honeynet-net:
