services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: honey_bee
      POSTGRES_PASSWORD: h1v3n!03
      POSTGRES_DB: honeycomb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata:
